import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { DatasetProvider } from './contexts/DatasetContext';
import Header from './components/Header';
import ThemeRegistry from './components/ThemeRegistry';
import { Suspense } from 'react';
import { ThemeProvider } from './contexts/ThemeContext';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Business Intelligence | FCC',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider>
          <ThemeRegistry>
            <DatasetProvider>
              <Suspense fallback={<div>Loading...</div>}>
                <Header />
              </Suspense>
              <Suspense fallback={<div>Loading...</div>}>
                {children}
              </Suspense>
            </DatasetProvider>
          </ThemeRegistry>
        </ThemeProvider>
      </body>
    </html>
  );
}
